# This is TOML file configuration for Database API's - KSH/GF Project

# Version information
title = "Gates Foundation Shapefile acess API"
version = 1.0

# Database login information
[Database]
Database_name = "niruthi_db"
Host = "bmgf-db.cutss4svfc0w.ap-south-1.rds.amazonaws.com"
User ="postgres"
Password = "Niruthi_2025!PG"
Port = 5432

